[general]
chrLenFile = /path/to/reference/hg38.fa.fai
ploidy = 2
breakPointThreshold = 0.8
window = 10000
chrFiles = /path/to/reference/split_chromosome_fasta/
outputDir = /path/to/output/controlfreec/
numberOfProcesses = 8
BedGraphOutput = FALSE
breakPointType = 1

[sample]
mateFile = /path/to/test_sample/test_sample.sorted.bam
inputFormat = bam
mateOrientation = 0

[control]
mateFile = /path/to/control_sample/control_sample.sorted.bam
inputFormat = bam
mateOrientation = 0
